### ISSUE TITLE
clean_tweets() function

### ISSUE THREAD

**Issue by shivajena** [UBC-MDS/tweetlytics#12]
# clean_tweets()

- This issue is related to the creating of the clean_tweets() function for cleaning the text in the tweets dataframe. 
- Input params: file path for .json or .csv file as per user input in get_store()
- Return: pandas df/ csv  containing two modified columns- one for cleaned words removing punctuation, and another for hastag count
- Depending on implementations, other things could include removal of stop words, n_grams, or any other pre-processing for feeding into ML preprocessors.

## To do list
- [x] #18

**Comment by mahsasarafrazi** [comment]
Thanks, Shiv. alongside the number of hashtags column, can you just keep hashtags as well? I need it for analytics part

**Comment by Amirshoja** [comment]
I will try to extract the hashtags as a separate feature from the API and place it in the Pandas Dataframe the get_store() returns.
I will confirm if this is possible in the next couple of days.
