### ISSUE TITLE
Package idea/topic

### ISSUE THREAD

**Issue by Amirshoja** [UBC-MDS/tweetlytics#2]
Hey everyone, 
As discussed everyone will ready 1-2 rough ideas surrounding the package topic by tomorrow 3PM.
Each proposal will include:
 - The general topic of the package
 - 4 functions to be included in the package
 - A name for the package

Also as discussed the data collection function can include working with public/open source APIs.

**Comment by shivajena** [comment]
My idea around the package topic is as follows:
 - General topic of the package: Fetches n images of a website (order may or maynot be random) and converts into a 4D numpy array. This can be useful in fetching logos or any kind of infographics from websites which have no restrictions such as public websites. If needed, we can also use energy functions as used in 512 to convert it into a energy matrix alongside simple numpy array.
 - the 4 functions broadly: 1. Fetch n number of images from a website; inputs: n, website link; tests: if the website is accessible or not, and accordingly the error message. 
  2. Convert into array - numpy or energy array as we wish. Or any other functionality
  3. Array transformations - can discuss on this - grayscale, any color, any filter, seamcarving may be.
  4. Printing the array, or any final analytics we want to show on the image.
 - A name for the package: ImageArray

**Comment by Amirshoja** [comment]
Hi everyone.

This is my proposal for the package topic. I am open to your ideas, just sending this before our 3pm meeting in case anyone wants to build on a similar idea.

**Our package name: Tweetlytics**
Retrieves tweets on a required topic and timeframe using the official twitter API, stores them as a .csv file, performs data cleaning, data analysis and plotting.

Function 1: get_store
Function 2: clean
Function 3: perform_analysis
Function 4: plots

Using this package we can then build a sample project on a specific word and present that as well.
