### ISSUE TITLE
Package Proposal (Approved by Andy)

### ISSUE THREAD

**Issue by Amirshoja** [UBC-MDS/tweetlytics#4]
**Package Name: Tweetlytics**

Retrieves tweets on a required topic and timeframe using the official twitter API, stores them as a .json and .csv file, performs data cleaning, data analysis and plotting.

**Function 1: get_store**
Utilizes the official Twitter API to collect data based on a keyword, date range and and number of results the user requires.
The data is then stored as a .Json file and a .csv file(optional). The function will also give the user the option to return a pandas data frame based on the stored files.

**Function 2: clean**
Takes the created pandas data frame from the get_store() function and will clean the data frame based on the required_cols, keep_punctuation, only_words… parameters entered by the user.

**Function 3: perform_analysis**
Takes the cleaned data frame from the clean() function and returns an analysis dict report including mean_word_count, most used words, mean_likes, most_used_hashtags, word_hashtag_ratio …

**Function 4: plotting**
Taking both the cleaned data frame from the clean() function and the returned dict from the perform_analysis() function, a range of plots such as word cloud, likes_wordcount, likes_hashtags… will be generated and saved as files.

Notes:
- As working with the Twitter API requires a personal ‘bearer token’ a user can create their own token and add it as a parameter to the get_store() function. 

- The package will also include a sample .Json and .csv file for reviewers to work with the other functions.
A sample project based on the keyword ‘omicron’ will be added to the package github.

**Comment by shivajena** [comment]
Thank you Amir for putting this up nicely. 
Inviting @andytai7  to weigh in his thoughts on our proposal and acceptance of the topic.

**Comment by andytai7** [comment]
Hi @shivajena and @Amirshoja. I think this is a great idea! I have also spoken to @Amirshoja through slack, and have accepted this idea!

Best, 
Andy
