### ISSUE TITLE
Analytics Function

### ISSUE THREAD

**Issue by mahsasarafrazi** [UBC-MDS/tweetlytics#6]
Hi team,

For the analytics function below you can find my ideas, feel free to comment on them. I will add my comments on some of them so that you can give me your feedback:

- f_m_ratio: ratio of females and males who tweet the keyword
- Country_ratio: ratio of countries that use the keyword in their tweets

    I am not sure whether tweeter gives us the above information.

- most_used_words: most frequent word in tweets with this keyword
- mean_likes: average likes of the tweets with this keyword
- most_used_hashtags: most frequent hashtags in tweets with this keyword

**Comment by Amirshoja** [comment]
Thanks @mahsasarafrazi. 
Good ideas are included. 

I have added issue #8 and provided a raw sample I have fetched from the Twitter API. You can take a look at that and make changes or updates to your ideas.

Thank you

**Comment by shivajena** [comment]
Thanks Mahsa. This looks really interesting. We can further brainstorm on this when we have a first basic run in future milestones
