### ISSUE TITLE
Data Sample from Twitter API

### ISSUE THREAD

**Issue by Amirshoja** [UBC-MDS/tweetlytics#8]
Please find below a raw sample of the data I have retrieved through the Twitter API. 
Kindly keep this as a basic reference and refer to it when designing other functions.
I will update this issue if any changes are made.

Important fields from the API response: text, created_at, retweet_count, reply_count, like_count, like_count, quote_count

# API response --------------------
{"author_id":"1257388407598301185",
"conversation_id":"1480328521746505729",
"public_metrics":{"retweet_count":849,"reply_count":0,"like_count":0,"quote_count":0},
"created_at":"2022-01-09T23:59:57.000Z",
"lang":"en",
"source":"Twitter for iPhone",
"id":"1480328521746505729",
"referenced_tweets":[{"type":"retweeted","id":"1480155356017958915"}],
"text":"RT @BitcoinMagazine: #Bitcoin isn\'t a get rich quick scheme, it\'s a don\'t get poor slowly strategy. \xe2\x9c\xa8","reply_settings":"everyone"},

**Comment by mahsasarafrazi** [comment]
Thanks, amir for sharing this, based on this data, I think country and gender would be deleted from analytics. Instead, the average number of retweets and the average number of comments can be added.
