### ISSUE TITLE
Team contract

### ISSUE THREAD

**Issue by mahm00d27** [UBC-MDS/tweetlytics#9]
Just shared the draft team contract through google doc. Please check your gmail inbox. I am leaving a link here, too. We will upload this on Saturday. So any changes are welcome before 10 PM, Friday.
Link: https://docs.google.com/document/d/1tV_sIjb5nGK30gvAJcOXZDYRi5aFYskz7FKUCYLkOzY/edit?usp=sharing

**Comment by mahsasarafrazi** [comment]
I have reviewed it Mahmood Thanks that is approved from my side.
